var m = require("mithril")
var state = {
    selected: {},
    getSelectionClass: function(inicial, selected, index){
        var str = (index == inicial)? "valueIni " : ""
        str += (index == selected)? "valueSel " : ""
        return str
    },
    magnitudes: ["Nivel 1","Nivel 2","Nivel 3","Nivel 4","Nivel 5","Nivel 10","Nivel 15","Nivel 20","Nivel 25","Nivel 30","Nivel 35","Nivel 40","Nivel 45","Nivel 50","Nivel 55","Nivel 60","Nivel 65"],
    ranges: ["Personal", "Toque/Mirada", "Adyacente", "Cerca", "Lejos", "Visual", "Conexion arcana"],
    durations: ["Momentaneo", "Concentracion/Diametro", "Solar", "Lunar/Anillo", "Estacional", "Anual", "Permanente/Instantaneo"],
    targets: ["Pequeño", "Individuo", "Grupo/Sala", "Circulo/Estructura", "Limite", "Visual"],
    tecnicas: ["Creo", "Intellego", "Muto", "Perdo", "Rego"],
    formas: ["Animal", "Aquam", "Auram", "Corpus", "Herbam", "Ignem", "Imaginem", "Mentem", "Terram", "Vim"],
    combo: {
        "Creo" : {
            "Animal" : 	{range : 1, duration: 2, target: 1, pag: "107", dscr: "", magn: "Level 3: Create the corpse of a tiny animal (Size -5/-4).#Level 4: Create the corpse of a small animal (Size -3/-2).#Level 5: Create the corpse of a medium animal (Size -1/0/+1). Create an insect.#Level 10: Create the corpse of a large animal (Size +2/+3). Create a tiny living animal.#Level 15: Create the corpse of a very large animal (Size +4/+5). Stop the progress of a disease.#Level 20: Heal one Body level of damage.#Level 25: Create a small animal.#Level 30: Create a medium animal. Create a tiny magical beast. Create a swarm of insects. Heal two Body levels of damage. Restore a lost sense. Restore a lost limb. Cure a disease, counteracting its effects.#Level 35: Create a large living animal. Create a small magical beast. Heal four Body levels of damage.#Level 40: Create a very large living animal. Create a medium magical beast. Heal six Body levels of damage.#Level 45: Create a large magical beast. Heal eight Body levels of damage.#Level 50: Create a very large magical beast. Heal ten Body levels of damage.#Level 55: Create a dragon. Heal twelve Body levels of damage. Level 60: Raise an animal from the dead (Ritual)."},
            "Aquam" : 	{range : 3, duration: 2, target: 0, pag: "113", dscr: "", magn: "General: Create poison that does +(Level) damage (Corpus or Animal requisite). Create a liquid that does +(Level - 5) damage on contact (Corpus or Animal requisite).#Level 5: Fill a anmade container with water (or some other natural liquid, with appropriate requisites).#Level 10: Create water (or some other natural liquid) that is not contained (for example, spread over a surface). Create a slightly unnatural liquid.#Level 15: Create water (or some other natural liquid) in an unnatural shape (for example, in a sphere over someone's head) or in an unnatural location (like within someone's lungs)-but water so created will behave normally. Create an extremely unnatural liquid.iquid.#Level 20: Create poison that causes a minor illness.#Level 25: Create a small spring. Create poison that causes major illness.#Level 30: Create poison that is fatal."},
            "Auram" : 	{range : 5, duration: 0, target: 4, pag: "118", dscr: "", magn: "Level 5: Create a draft.#Level 10: Create a breeze.#Level 15: Create a wind. Create a fog. Level 20: Create a squall.#Level 25: Create a thunderstorm. Level 30: Create a tempest.#Level 45: Create a hurricane.#Level 60: Create lightning."},
            "Corpus" : 	{range : 1, duration: 2, target: 1, pag: "123", dscr: "", magn: "Level 5: Prevent decay of a body.#Level 10: Create an entire human corpse. Stabilize one wound.#Level 15: Stop the progress of a disease.#Level 20: Heal one Body level of damage.#Level 25: Heal the damage caused by a poison or disease.#Level 30: Restore a lost limb. Heal two Body levels of damage.#Level 35: Heal four Body levels of damage.#Level 40: Heal all harm done to a body.#Level 50: Return 'life' to a corpse (Ritual)-See The Shadow of Life Renewed."},
            "Herbam" : 	{range : 3, duration: 2, target: 1, pag: "132", dscr: "", magn: "Level 5: Create a plant product (like a fruit or leaf). Create a plant. Prevent a plant from becoming sick.#Level 10: Create a bush or a pile of sticks or brambles. Prevent a bush from becoming sick.#Level 15: Create a tree. Create wood. Prevent a tree from becoming sick. Prevent wood from rotting."},
            "Ignem" : 	{range : 3, duration: 0, target: 0, pag: "137", dscr: "", magn: "Level 1: Ignite something extremely flammable (like oil or a wick). Illuminate an area as if by moonlight. Heat an object so that it is warm to the touch.#Level 3: Ignite something very flammable (like parchment). Illuminate an area as if by candlelight. Heat an object to be hot to the touch.#Level 5: Create a fire intense enough to do +5 damage (a Small flame can only affect a single target). Ignite something flammable (like dry wood or charcoal). Illuminate an area as if by torchlight. Heat an object enough to boil water.#Level 10: Create a fire doing +5 damage in an unnatural shape (like a ring or sheet). Create a fire doing +10 damage. Ignite something slightly flammable (like damp wood or leather). Illuminate an area as if by daylight on a cloudy day. Heat an object enough to make it glow redhot.#Level 15: Create a fire doing +10 damage in an unnatural shape. Create a fire doing +15 damage. Ignite something barely flammable (like a human body). Illuminate an area as if by full sunlight. Heat an object enough to melt lead.#Level 20: Create a fire doing +20 damage. Heat an object enough to melt steel.#Level 25: Create a fire doing +25 damage. Level 30: Create a fire doing +30 damage."},
            "Imaginem" :{range : 2, duration: 2, target: 1, pag: "142", dscr: "", magn: "Level 5: Create an image that affects a single sense. Level 10: Create an image that affects two senses. Level 15: Create an image that affects three senses. Level 20: Create an image that affects four senses. Level 25: Create an image that affects five senses."},
            "Mentem" : 	{range : 1, duration: 2, target: 1, pag: "148", dscr: "", magn: "Level 5: Form words in another's mind.#Level 10: Put a thought into another's mind.#Level 15: Create an emotion in another's mind.#Level 20: Create a memory in another's mind.#Level 25: Effectively increase another person's ability to think."},
            "Terram" : 	{range : 3, duration: 2, target: 0, pag: "153", dscr: "", magn: "Level 5: Create an amount of sand, dirt, mud, or clay. Level 10: Create an amount of stone or glass.#Level 15: Create an amount of metal or a rough gemstone. Level 20: Create an amount of polished gemstone."},
            "Vim" : 	{range : 1, duration: 2, target: 1, pag: "159", dscr: "", magn: ""},
        },
        "Intellego" : {
            "Animal" : 	{range : 1, duration: 1, target: 1, pag: "108", dscr: "", magn: "Level 1: Get a mental image of an animal.#Level 5: Sense the state of consciousness of a beast. Get general information about its body.#Level 10: Sense the dominant drive of a beast. Learn a specific fact about its body.#Level 15: Learn the origin, age, and history of something made of animal products.#Level 20: Speak with an animal (Auram requisite for birds, Aquam requisite for fish). Read an animal's surface thoughts.#Level 25: Read the recent memories of a beast.#Level 30: Thoroughly probe the mind of a beast."},
            "Aquam" : 	{range : 1, duration: 1, target: 0, pag: "114", dscr: "", magn: "Level 1: Get an image of water within range.#Level 3: Get an images of water and its immediate surroundings within range.#Level 5: Learn the natural properties of a liquid.#Level 10: Learn the natural properties of a mixture of liquids.#Level 15: Learn the magical properties of a liquid. Make your senses unaffected by water.#Level 20: Learn the magical properties of a mixture of liquids.#Level 25: Speak with a natural body of water.#Level 30: Speak with an artificial body of water (like a fountain)."},
            "Auram" : 	{range : 0, duration: 1, target: 2, pag: "120", dscr: "", magn: "Level 5: Sense one property of air (for example, determine if it is safe to breathe).#Level 10: Learn all mundane properties of the air. Have an intuition about some fact regarding the air.#Level 15: Make your senses unhindered by the air (for exam- ple, you can hear over a howling wind).#Level 20: Predict the weather. Level 25: Speak with air."},
            "Corpus" : 	{range : 5, duration: 0, target: 1, pag: "125", dscr: "", magn: "Level 5: Sense very general information about a body.#Level 10: Sense a specific piece of information about a body. Level 15: Locate a person you have an arcane connection to. Level 20: Sense all useful information about a body.#Level 25: Speak with a dead body."},
            "Herbam" : 	{range : 1, duration: 1, target: 1, pag: "132", dscr: "", magn: "Level 3: Gain an intuitive knowledge of a plant (for example, know whether a given action would harm a plant).#Level 5: Learn general information, or a single specific fact about a plant or an item made from plant products.#Level 10: Learn all mundane properties of a plant or an item made from plant products.#Level 15: Sense or locate plants you cannot otherwise perceive.#Level 25: Speak with a plant."},
            "Ignem" : 	{range : 2, duration: 1, target: 0, pag: "139", dscr: "", magn: "Level 4: Sense one property of a fire. Locate a fire.#Level 5: Sense all mundane properties of a fire. Become aware of all fires within the target area. See a fire with which you have an arcane connection.#Level 10: Sense all mundane properties of ash. See a fire you have an arcane connection to and all things it illuminates (for example, see a campfire and everything within its circle of light).#Level 15: See clearly through raging fire (an Auram requisite may be necessary if smoke is present as well). Learn the magical properties of a fire.#Level 25: Speak with a fire."},
            "Imaginem" :{range : 3, duration: 1, target: 2, pag: "143", dscr: "", magn: "Level 5: Use one sense at a distance. Memorize or perfect your memory about an image you have encountered. Be able to discern your own false images.#Level 10: Use two senses at a distance.#Level 15: Use three senses at a distance.#Level 20: Use four senses at a distance. See up to five years into the past.#Level 25: Use all senses at a distance."},
            "Mentem" : 	{range : 1, duration: 0, target: 1, pag: "149", dscr: "", magn: "Level 5: Sense the state of consciousness of one intelligent being (for example, asleep, awake, meditating, dead, drugged, insane, or comatose).#Level 10: Sense a single emotion in a being.#Level 15: Sense all of the emotions in a being. Discover the truth of a statement.#Level 20: Speak with any one human. Read a person's surface thoughts. Pick a single answer from the mind of a target.#Level 25: Read the last day's memories from one person.#Level 30: Learn all the information you wish from a person's mind."},
            "Terram" : 	{range : 2, duration: 1, target: 0, pag: "154", dscr: "", magn: "Level 2: Learn one visible property of an object (a property that someone with appropriate skills could determine just by looking).#Level 4: Learn one mundane property of an object. See an object and its surroundings.#Level 5: Learn all components of a mixture or alloy (you must know the components before divining the properties).#Level 10: Learn all the natural properties of an object.#Level 15: Sense all the mundane properties of a composite#object.#Level 20: Learn the magical properties of an object. Make your senses unhindered by earth (for example, see right through a rock).#Level 30: Speak with a natural rock (for example, a boulder). Level 35: Speak with an artificial rock (for example, a statue). Level 45: See an object and its surroundings in the past."},
            "Vim" : 	{range : 3, duration: 1, target: 1, pag: "160", dscr: "", magn: ""},
        },
        "Muto" : {
            "Animal" : 	{range : 1, duration: 2, target: 1, pag: "109", dscr: "", magn: "Level 3: Make a superficial change to something made of animal products (like changing its color).#Level 5: Make a major change to something made of animal products that preserves the substance (for example, turn a leather jerkin into a saddle). Gradually turn meat into vermin. Make a superficial change to a beast.#Level 10: Change an animal's limb.#Level 15: Make a major change in a beast, while leaving it rec- ognizably the same sort of animal (for example, make a horse bigger and change its color).#Level 20: Change an animal into a different animal. Change an animal in a minor way so that it is no longer natural (for example, change the color of a horse's coat to match the covenant's coat of arms).#Level 25: Change an animal into a human (though it retains its animal mentality and does not gain a soul). Change an animal into a plant (requires an Herbam requisite).#Level 30: Change an animal in a major unnatural way (for example, give a horse claws, fangs, and scaly armored skin). Change an animal into a non-living item (appropri- ate requisite required).#Level 40: Radically change an animal in an unnatural way (for example, give a horse wings). Give an animal a 'magical' ability, such as the ability to breathe fire (requires a requi- sisite for the ability)."},
            "Aquam" : 	{range : 1, duration: 2, target: 0, pag: "115", dscr: "", magn: "General: Change a liquid into a poison doing +(Level + 5) points of damage (Corpus or Animal requisite). Change a liquid into a liquid that does +(Level) points of damage on contact (Corpus or Animal requisite).#Level 3: Change a characteristic of liquid within that liquid's normal range (for example, make water pure or stagnant).#Level 4: Change a natural liquid into another natural liquid.#Level 5: Change a liquid into a corresponding solid (Terram requisite) or gas (Auram requisite) (for example, water to ice or steam). Change a natural liquid into a slightly unnatural liquid (for example, make blue water or strawberry flavored castor oil), or vice versa.#Level 10: Change a liquid into an unrelated solid or gas (with requisites). Change a natural liquid into two or more different natural liquids, with the two types separate (although they will mix again normally). Change a liquid into a very unnatural liquid (for example, a shocking pink liquid that causes bizarre hallucinations)-requisites will often be required.#Level 15: Change a liquid into a mixture of any liquid, solid (with Terram requisite), or gas (with Auram requisite). Change a liquid into a slightly unnatural solid or gas.#Level 20: Change a liquid into a very unnatural solid or gas."},
            "Auram" : 	{range : 3, duration: 0, target: 0, pag: "120", dscr: "", magn: "Level 4: Double or halve the intensity of a manifestation of air.#Level 5: Transform an amount of air into another form of air.#Level 10: Transform an amount of air into another element. Transform an amount of air into a gas that does +5 damage.#Level 15: Transform an amount of air into a mixture of elements. Transform an amount of air into something slightly unnatural (for example, into silvery fog or a specific shape).#Level 20: Transform an amount of air into something wholly unnatural (for example, transform a cloud into a horse shape that gallops across the sky)."},
            "Corpus" : 	{range : 1, duration: 2, target: 1, pag: "126", dscr: "", magn: "Level 5: Change a small part of a person (for example, an eye or nose).#Level 10: Change a limb of a person. Level 15: Change the face of a person.#Level 20: Utterly change the appearance or size of a person (though they must still remain human in form). Make a body resistant to damage (+5 Soak).#Level 25: Turn a human into a land animal (with an Animal requisite).#Level 30: Make body resistant to damage (+10 Soak).#Level 35: Turn a human into a bird or a fish (Animal reisite).#Level 40: Turn a human into a solid inanimate object (Terram requisite). Turn a human into a plant (Herbam requisite).#Level 45: Turn a human into an insubstantial object (Auram requisite)."},
            "Herbam" : 	{range : 1, duration: 2, target: 0, pag: "133", dscr: "", magn: "Level 5: Change a plant or item made from plant products. Level 10: Change a plant or item made from plant products#into metal or stone (Terram requisite).#Level 15: Cause a plant to bend or twist rapidly in place. Level 20: Affect the consciousness and spirit of a plant."},
            "Ignem" : 	{range : 2, duration: 1, target: 1, pag: "139", dscr: "", magn: "Level 3: Change one characteristic of a fire within the target area (for example, make a fire burn more brightly, or produce more smoke).#Level 4: Totally change a fire into another natural fire (changing any or all of its characteristics).#Level 5: Change a fire so that it is slightly unnatural (for example, make the flames colored, or make the smoke smell of roses). May require requisites.#Level 10: Change a fire so that it is completely unnatural (for example, multicolored flames that form images while the popping of the fire plays music). Often requires requisites.#Level 15: Change a fire into natural air (Auram requisite). Level 20: Change a fire into a natural solid (Terram requisite).#Change a fire into slightly unnatural air.#Level 30: Change a fire into a natural liquid (Aquam requisite). Change a fire into very unnatural air."},
            "Imaginem" :{range : 3, duration: 2, target: 1, pag: "144", dscr: "", magn: "Level 4: Heighten or lessen one sensation of an object (for example, make a candy more sweet or less sweet).#Level 5: Change one sensation of an object (for example, make a leaf look like a coin), but not its type.#Level 10: Change two sensations of an object.#Level 15: Change three sensations of an object.#Level 20: Change four sensations of an object.#Level 25: Change an object completely, in all things except touch.#Level 30: Completely distort the sensory perceptions of a target."},
            "Mentem" : 	{range : 1, duration: 2, target: 1, pag: "150", dscr: "", magn: "Level 4: Force a ghost to become visible (provided that it can do so normally).#Level 5: Make a minor change in a person's memory of an event.#Level 10: Make a major change to a person's memory of an event. Make a minor change to a person's emotion.#Level 15: Make a major change to a person's memory of a series of events. Make a major change to a person's emotion.#Level 20: Make major changes to a person's memory of a peri- odod of his life. Completely change a person's emotions.#Level 30: Completely rewrite a person's memories. Utterly change a person's mind."},
            "Terram" : 	{range : 2, duration: 2, target: 0, pag: "155", dscr: "", magn: "Level 3: Change the shape of of dirt.#Level 4: Change one property of dirt.#Level 5: Change dirt to another type of natural earth (for example, sand to loam).#Level 10: Change dirt so that it is slightly unnatural (requisites may be required). Change dirt into a liquid or gas (with requisites). Change dirt to stone, or vice versa.#Level 15: Change dirt so that it is highly unnatural (requisites will often be required). Change dirt into a mixture of liquids, solids, and gases (with requisites).#Level 20: Change dirt into a slightly unnatural liquid or gas (with requisites).#Level 25: Change dirt into a highly unnatural liquid or gas (with requisites)."},
            "Vim" : 	{range : 2, duration: 0, target: 1, pag: "161", dscr: "", magn: ""},
        },
        "Perdo" : {
            "Animal" : 	{range : 1, duration: 6, target: 1, pag: "110", dscr: "", magn: "Level 3: Damage something made of animal products.#Level 5: Do superficial damage to a beast (for example, remove#its hair). Destroy something made of animal products.#Level 10: Cause a beast pain, but do no real damage.#Level 15: Do 1 Body level of damage. Destroy a beast's limb.#Level 20: Destroy one of a beast's senses. Do 2 Body levels of damage.#Level 25: Do 4 Body levels of damage. Level 35: Kill an animal."},
            "Aquam" : 	{range : 1, duration: 6, target: 0, pag: "116", dscr: "", magn: "Level 5: Destroy a liquid (requisites may be required).#Level 15: Destroy one property of a liquid (like alcohol's ability to intoxicate or sea water's saltiness).#Level 20: Destroy a Small spring, so that it never flows again.#Level 40: Destroy a lake, drying the bed and preventing water from ever naturally pooling there (channels for runoff are also created)-Ritual."},
            "Auram" : 	{range : 1, duration: 0, target: 1, pag: "121", dscr: "", magn: "Level 5: Destroy an amount of air. Stop very minor weather phenomena, like breezes.#Level 20: Stop any one part of a weather phenomenon (for example, stop lightning from striking during a thunder-storm).#Level 30: Stop any weather phenomenon, excluding those caused by Ritual magic."},
            "Corpus" : 	{range : 3, duration: 0, target: 1, pag: "128", dscr: "", magn: "Level 5: Do superficial damage to a body (for example, remove its hair).#Level 10: Cause a person pain, but do no real damage. Cause the loss of one Fatigue level.#Level 15: Do one Body level of damage to a person. Destroy a person's limb. Destroy a corpse.#Level 20: Destroy one of a person's major senses. Do two Body levels of damage.#Level 25: Age someone five years. Do three Body levels of damage.#Level 30: Inflict a major disease. Do four Body levels of damage. Level 40: Kill a person."},
            "Herbam" : 	{range : 2, duration: 6, target: 0, pag: "135", dscr: "", magn: "Level 4: Spoil an amount of food.#Level 5: Destroy an amount of dead wood. Cause the leaves to#fall off of a plant. Level 10: Destroy a plant."},
            "Ignem" : 	{range : 2, duration: 0, target: 0, pag: "140", dscr: "", magn: "Level 3: Greatly reduce the amount of light in an area.#Level 4: Completely extinguish all light in an area.#Level 5: Extinguish a fire, cooling the ashes to merely warm. Chill an object.#Level 10: Strongly chill an object. Destroy one aspect of a fire (for example, heat or light)."},
            "Imaginem" :{range : 2, duration: 2, target: 1, pag: "145", dscr: "", magn: "Level 5: Destroy an object's ability to affect a single sense. Level 10: Destroy an object's ability to affect two senses. Level 15: Destroy an object's ability to affect three senses. Level 20: Destroy an object's ability to affect four senses. Level 25: Destroy an object's ability to affect five senses."},
            "Mentem" : 	{range : 1, duration: 2, target: 1, pag: "150", dscr: "", magn: "Level 5: Remove a minor detail from a person's memory. Level 10: Remove an important detail from a person's mememory.#Level 15: Quell an emotion in a person. Diminish a single mental capability in a person.#Level 20: Remove a minor or short memory from a person's mind.#Level 25: Remove a major or long memory from a person's mind. Reduce all of a person's mental capabilities.#Level 30: Remove all emotions from a person. Drive a person insane.#Level 40: Leaves a person a mindless husk."},
            "Terram" : 	{range : 2, duration: 0, target: 0, pag: "156", dscr: "", magn: "Level 3: Destroy one property of dirt. #Level 4: Destroy dirt."},
            "Vim" : 	{range : 2, duration: 6, target: 1, pag: "163", dscr: "", magn: ""},
        },
        "Rego" : {
            "Animal" : 	{range : 1, duration: 1, target: 1, pag: "111", dscr: "", magn: "Level 4: Manipulate items made from animal products.#Level 5: Plant a single suggestion in the mind of an animal. Protect the target from animal attacks (affects normal animals only).#Level 10: Calm an animal.#Level 15: Manipulate an animal's emotions. Paralyze an animal.#Level 20: Make an animal completely passive. .#Level 25: Completely control an animal."},
            "Aquam" : 	{range : 3, duration: 1, target: 0, pag: "116", dscr: "", magn: "Gen: Ward against Faerie creatures of water whose might is less than or equal to the level of the spell (duration Ring, target Group).#Level 5: Control a liquid in a natural fashion (for example, control direction or speed of flow).#Level 10: Control a liquid in a slightly unnatural fashion (for example, make it flow uphill or stop it from wetting something). Control an amount of liquid which is part of a larger body in a natural fashion.#Level 15: Control a liquid in a highly unnatural fashion (for example, make it flow straight up in the air or take on a humanoid form). Control an amount of liquid which is part of a larger body in a slightly unnatural fashion.#Level 20: Control an amount of liquid which is part of a larger body in a highly unnatural fashion."},
            "Auram" : 	{range : 3, duration: 1, target: 1, pag: "122", dscr: "", magn: "Gen: Ward against Faerie creatures of the air whose Might is less than or equal to the level of the spell (duration Ring, target Group)#Level 5: Control an amount of air.#Level 10: Control an amount of air with great force.#Level 20: Direct weather in progress. Control an amount of air with enough force to uproot small trees.#Level 30: Cause clouds to produce rain. Control an amount of air with enough force to uproot large trees."},
            "Corpus" : 	{range : 3, duration: 1, target: 1, pag: "130", dscr: "", magn: "Level 5: Make a target lose control of a body part.#Level 15: Control the large-scale physical movements of a target.#Level 20: Hold a target's the body motionless.#Level 25: Control a target's motions. Eliminate the penalties of fatigue and wounds.nds.#Level 30: Direct the flow of bodily energy.#Level 50: Teleport a target's body to a place you have an arcanene connection to. Teleport a target's body seven leagues."},
            "Herbam" : 	{range : 2, duration: 1, target: 0, pag: "135", dscr: "", magn: "Level 5: Control an amount of wood (for example, a branch or a wooden weapon).#Level 10: Deflect a single attack by a wooden weapon.#Level 15: Deflect several attacks by wooden weapons.#Level 20: Deflect all known attacks by wooden weapons. Cause a Small amount of wood (for example, a wooden weapon, small plant, or branch) to move around as you direct it, though if it is a rooted plant, it remains rooted.#Level 25: Deflect all attacks by wooden weapons, both seen and unseen. Cause a Small amount of wood (for example, a wooden weapon, small plant, or branch) to move around as you direct it (it need not remain rooted)."},
            "Ignem" : 	{range : 2, duration: 1, target: 0, pag: "141", dscr: "", magn: "Level 5: Control a fire in a natural fashion (for example, control its direction of spread).#Level 10: Control a fire in a slightly unnatural fashion (for example, stop it from burning a person).#Level 20: Control a fire in a very unnatural fashion (for example, fashion into a dancing humanoid shape)."},
            "Imaginem" :{range : 2, duration: 2, target: 1, pag: "146", dscr: "", magn: "Level 5: Make an object appear (to one sense) to be up to one pace away from its actual position.#Level 10: Make an object appear (to one sense) to be up to five paces away from its actual position.#Level 15: Make an object appear (to one sense) to be up to in Near range of its actual position. Make an object appear (to one sense) to be contained in or attached to another object defined at the time of casting (for example, make someone's voice appear to come from within a bag).#Level 20: Make an object appear (to one sense) to be in Far range of its actual position.#Level 25: Make an object appear (to one sense) to be in Sight of its actual position.#Level 30: Make an object appear (to one sense) to be in a location that the caster has an arcane connection to."},
            "Mentem" : 	{range : 1, duration: 2, target: 1, pag: "152", dscr: "", magn: "Level 10: Control a target's mental state (for example, awake, asleep, or confused)#Level 15: Control a natural emotion (for example, calm, fear). The target must feel the emotion before you can control it.#Level 20: Control an unnatural emotion (for example, cultivate a person's feelings of bravery where he is usually cowardly).#Level 25: Control a human being as long as you can see him. #Level 30: Give a person one complex command, which he#tries to carry out to the best of his ability.#Level 40: Completely control a person's mind and emotions."},
            "Terram" : 	{range : 3, duration: 1, target: 0, pag: "157", dscr: "", magn: "Level 5: Control or move dirt.#Level 10: Deflect a single attack by a metal weapon.#Level 15: Teleport dirt up to 15 paces. Deflect several attacks from metal weapons.#Level 20: Deflect all metal weapon attacks against you that you are aware of.#Level 25: Keep metal objects completely away from your person (that is, deflect all attacks against you from metal weapons, whether you are aware of them or not)."},
            "Vim" : 	{range : 3, duration: 1, target: 1, pag: "164", dscr: "", magn: ""},
        },
    }
}


module.exports = state

